"""add_activity_log_model

Revision ID: 0546d802985e
Revises: e469c3324507
Create Date: 2026-07-19 21:14:59.409552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0546d802985e'
down_revision: Union[str, None] = 'e469c3324507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rm_tran_no', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('THIRD_MONTH_DECISION', 'FIFTH_MONTH_DECISION', 'EXTENSION_DECISION', 'UPLOAD_URL_ISSUED', name='activity_log_action'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', name='activity_log_status'), nullable=False),
    sa.Column('actor_type', sa.Enum('INTERNAL', 'EXTERNAL', name='activity_log_actor_type'), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('bu_group', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_rm_tran_no'), 'activity_logs', ['rm_tran_no'], unique=False)
    op.alter_column('performance_appraisals', 'fifth_month_decision',
               existing_type=mysql.ENUM('REGULARIZATION', 'NON_REGULARIZATION', 'EXTENSION', 'NO_APPRAISAL'),
               type_=sa.Enum('REGULARIZATION', 'NON_REGULARIZATION', 'NO_APPRAISAL', 'EXTENSION', name='fifth_month_decision'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance_appraisals', 'fifth_month_decision',
               existing_type=sa.Enum('REGULARIZATION', 'NON_REGULARIZATION', 'NO_APPRAISAL', 'EXTENSION', name='fifth_month_decision'),
               type_=mysql.ENUM('REGULARIZATION', 'NON_REGULARIZATION', 'EXTENSION', 'NO_APPRAISAL'),
               existing_nullable=True)
    op.drop_index(op.f('ix_activity_logs_rm_tran_no'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
