"""add_authorized_domains

Revision ID: 7efeed0a4cbd
Revises: 4150b630dd7f
Create Date: 2026-06-04 15:23:46.005727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7efeed0a4cbd'
down_revision: Union[str, None] = '4150b630dd7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorized_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index(op.f('ix_authorized_domains_id'), 'authorized_domains', ['id'], unique=False)
    op.alter_column('user_tokens', 'expires_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_tokens', 'expires_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_index(op.f('ix_authorized_domains_id'), table_name='authorized_domains')
    op.drop_table('authorized_domains')
    # ### end Alembic commands ###
