"""appraisal_notification_models

Revision ID: 85cf48df6e7a
Revises: 7efeed0a4cbd
Create Date: 2026-07-02 13:30:50.816528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85cf48df6e7a'
down_revision: Union[str, None] = '7efeed0a4cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_type', sa.Enum('BU_GROUP', 'ROLE', name='recipient_type'), nullable=False),
    sa.Column('recipient_value', sa.String(length=255), nullable=False),
    sa.Column('milestone', sa.String(length=255), nullable=False),
    sa.Column('rm_tran_no', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_rm_tran_no'), 'notifications', ['rm_tran_no'], unique=False)
    op.create_table('performance_appraisals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rm_tran_no', sa.Integer(), nullable=False),
    sa.Column('erms_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_sdate', sa.Date(), nullable=False),
    sa.Column('bu_tagging', sa.String(length=255), nullable=False),
    sa.Column('third_month_due_date', sa.Date(), nullable=True),
    sa.Column('third_month_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('third_month_decision', sa.Enum('PROCEED_5TH', 'NON_REGULARIZATION', name='third_month_decision'), nullable=True),
    sa.Column('third_month_appraisal_file_key', sa.String(length=1024), nullable=True),
    sa.Column('third_month_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('third_month_decided_by', sa.Integer(), nullable=True),
    sa.Column('fifth_month_due_date', sa.Date(), nullable=True),
    sa.Column('fifth_month_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fifth_month_decision', sa.Enum('REGULARIZATION', 'NON_REGULARIZATION', 'EXTENSION', name='fifth_month_decision'), nullable=True),
    sa.Column('fifth_month_appraisal_file_key', sa.String(length=1024), nullable=True),
    sa.Column('fifth_month_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fifth_month_decided_by', sa.Integer(), nullable=True),
    sa.Column('extension_until', sa.Date(), nullable=True),
    sa.Column('extension_final_decision', sa.Enum('REGULARIZATION', 'NON_REGULARIZATION', name='extension_final_decision'), nullable=True),
    sa.Column('extension_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extension_decided_by', sa.Integer(), nullable=True),
    sa.Column('sixth_month_check_date', sa.Date(), nullable=True),
    sa.Column('failsafe_triggered', sa.Boolean(), nullable=True),
    sa.Column('failsafe_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failsafe_reason', sa.Enum('NO_3RD_MONTH_APPRAISAL', 'NO_5TH_MONTH_DECISION', 'EXTENSION_UNRESOLVED', name='failsafe_reason'), nullable=True),
    sa.Column('appraisal_status', sa.Enum('PENDING', 'FOR_REGULARIZATION', 'REGULARIZED', 'NON_REGULARIZED', 'NEEDS_REVIEW', 'RESOLVED_MANUAL', name='appraisal_status'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_reason', sa.Enum('LEFT_COMPANY', 'AWOL', 'TRANSFERRED', 'DATA_ERROR', 'OTHER', name='resolution_reason'), nullable=True),
    sa.Column('resolution_notes', sa.String(length=2000), nullable=True),
    sa.Column('resolution_resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['extension_decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fifth_month_decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolution_resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['third_month_decided_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_appraisals_bu_tagging'), 'performance_appraisals', ['bu_tagging'], unique=False)
    op.create_index(op.f('ix_performance_appraisals_rm_tran_no'), 'performance_appraisals', ['rm_tran_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_appraisals_rm_tran_no'), table_name='performance_appraisals')
    op.drop_index(op.f('ix_performance_appraisals_bu_tagging'), table_name='performance_appraisals')
    op.drop_table('performance_appraisals')
    op.drop_index(op.f('ix_notifications_rm_tran_no'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
