"""extension_record

Revision ID: a940066515fc
Revises: 85cf48df6e7a
Create Date: 2026-07-14 11:00:32.131815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a940066515fc'
down_revision: Union[str, None] = '85cf48df6e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appraisal_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('extension_until', sa.Date(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('decision', sa.Enum('REGULARIZATION', 'NON_REGULARIZATION', 'EXTENSION', name='extension_record_decision'), nullable=True),
    sa.Column('appraisal_file_key', sa.String(length=1024), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_id'], ['performance_appraisals.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extension_records_appraisal_id'), 'extension_records', ['appraisal_id'], unique=False)
    op.drop_constraint('performance_appraisals_ibfk_1', 'performance_appraisals', type_='foreignkey')
    op.drop_column('performance_appraisals', 'extension_final_decision')
    op.drop_column('performance_appraisals', 'extension_until')
    op.drop_column('performance_appraisals', 'extension_decided_by')
    op.drop_column('performance_appraisals', 'extension_decided_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_appraisals', sa.Column('extension_decided_at', mysql.DATETIME(), nullable=True))
    op.add_column('performance_appraisals', sa.Column('extension_decided_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('performance_appraisals', sa.Column('extension_until', sa.DATE(), nullable=True))
    op.add_column('performance_appraisals', sa.Column('extension_final_decision', mysql.ENUM('REGULARIZATION', 'NON_REGULARIZATION'), nullable=True))
    op.create_foreign_key('performance_appraisals_ibfk_1', 'performance_appraisals', 'users', ['extension_decided_by'], ['id'])
    op.drop_index(op.f('ix_extension_records_appraisal_id'), table_name='extension_records')
    op.drop_table('extension_records')
    # ### end Alembic commands ###
