"""appraisal_models

Revision ID: bf8f32b24cbe
Revises: 7efeed0a4cbd
Create Date: 2026-08-05 10:28:49.923719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8f32b24cbe'
down_revision: Union[str, None] = '7efeed0a4cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.Enum('THIRD_MONTH_DECISION', 'FIFTH_MONTH_DECISION', 'EXTENSION_DECISION', 'UPLOAD_URL_ISSUED', name='activity_log_action'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', name='activity_log_status'), nullable=False),
    sa.Column('actor_type', sa.Enum('INTERNAL', 'EXTERNAL', name='activity_log_actor_type'), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('bu_group', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_employee_id'), 'activity_logs', ['employee_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_type', sa.Enum('BU_GROUP', 'ROLE', name='recipient_type'), nullable=False),
    sa.Column('recipient_value', sa.String(length=255), nullable=False),
    sa.Column('milestone', sa.String(length=255), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_employee_id'), 'notifications', ['employee_id'], unique=False)
    op.create_table('performance_appraisals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_sdate', sa.Date(), nullable=False),
    sa.Column('bu_tagging', sa.String(length=255), nullable=False),
    sa.Column('third_month_due_date', sa.Date(), nullable=True),
    sa.Column('third_month_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('third_month_decision', sa.Enum('PROCEED_5TH', 'NON_REGULARIZATION', 'NO_APPRAISAL', name='third_month_decision'), nullable=True),
    sa.Column('third_month_appraisal_file_key', sa.String(length=1024), nullable=True),
    sa.Column('third_month_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('third_month_decided_by', sa.Integer(), nullable=True),
    sa.Column('fifth_month_due_date', sa.Date(), nullable=True),
    sa.Column('fifth_month_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fifth_month_decision', sa.Enum('REGULARIZATION', 'NON_REGULARIZATION', 'NO_APPRAISAL', 'EXTENSION', name='fifth_month_decision'), nullable=True),
    sa.Column('fifth_month_appraisal_file_key', sa.String(length=1024), nullable=True),
    sa.Column('fifth_month_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fifth_month_decided_by', sa.Integer(), nullable=True),
    sa.Column('sixth_month_check_date', sa.Date(), nullable=True),
    sa.Column('failsafe_triggered', sa.Boolean(), nullable=True),
    sa.Column('failsafe_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failsafe_reason', sa.Enum('NO_3RD_MONTH_APPRAISAL', 'NO_5TH_MONTH_DECISION', 'EXTENSION_UNRESOLVED', name='failsafe_reason'), nullable=True),
    sa.Column('appraisal_status', sa.Enum('PENDING', 'FOR_REGULARIZATION', 'REGULARIZED', 'NON_REGULARIZED', 'NEEDS_REVIEW', 'RESOLVED_MANUAL', name='appraisal_status'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_reason', sa.Enum('LEFT_COMPANY', 'AWOL', 'TRANSFERRED', 'DATA_ERROR', 'OTHER', name='resolution_reason'), nullable=True),
    sa.Column('resolution_notes', sa.String(length=2000), nullable=True),
    sa.Column('resolution_resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fifth_month_decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolution_resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['third_month_decided_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_appraisals_appraisal_status'), 'performance_appraisals', ['appraisal_status'], unique=False)
    op.create_index(op.f('ix_performance_appraisals_bu_tagging'), 'performance_appraisals', ['bu_tagging'], unique=False)
    op.create_index(op.f('ix_performance_appraisals_employee_id'), 'performance_appraisals', ['employee_id'], unique=True)
    op.create_table('extension_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appraisal_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('extension_until', sa.Date(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('decision', sa.Enum('REGULARIZATION', 'NON_REGULARIZATION', 'EXTENSION', name='extension_record_decision'), nullable=True),
    sa.Column('appraisal_file_key', sa.String(length=1024), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_id'], ['performance_appraisals.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extension_records_appraisal_id'), 'extension_records', ['appraisal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extension_records_appraisal_id'), table_name='extension_records')
    op.drop_table('extension_records')
    op.drop_index(op.f('ix_performance_appraisals_employee_id'), table_name='performance_appraisals')
    op.drop_index(op.f('ix_performance_appraisals_bu_tagging'), table_name='performance_appraisals')
    op.drop_index(op.f('ix_performance_appraisals_appraisal_status'), table_name='performance_appraisals')
    op.drop_table('performance_appraisals')
    op.drop_index(op.f('ix_notifications_employee_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_activity_logs_employee_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
